version: '3.9'

services:
  ssserver:
    image: pexcn/docker-images:shadowsocks-rust
    container_name: ssserver
    network_mode: host
    restart: unless-stopped
    environment:
    logging:
      options:
        max-file: 1
        max-size: 20m
      TZ: Asia/Shanghai
      CHILLING_EFFECT: 0
      SHADOWSOCKS_PASSWORD_1: password_1
      SHADOWSOCKS_PASSWORD_2: password_2
    volumes:
      - ./shadowsocks-rust-data:/etc/shadowsocks-rust
      #- ../../utils/acme.sh/acme.sh-data/example.com_ecc:/.acme.sh/example.com
    command: ssservice server --user nobody --config /etc/shadowsocks-rust/server.json

  sslocal:
    image: pexcn/docker-images:shadowsocks-rust
    container_name: sslocal
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      CHILLING_EFFECT: 0
      SHADOWSOCKS_PASSWORD_1: password_1
      SHADOWSOCKS_PASSWORD_2: password_2
    volumes:
      - ./shadowsocks-rust-data:/etc/shadowsocks-rust
    command: ssservice local --config /etc/shadowsocks-rust/local.json
