version: '3.9'

services:
  nginx:
    #image: linuxserver/nginx
    image: nginx:1.23.1-alpine
    container_name: nginx
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      #use linuxserver images
      #PUID: 99
      #PGID: 100
      #UMASK: 022
    volumes:
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      - /mnt/user/appdata/acme.sh:/cert
