version: '3.9'

services:
  nextcloud:
    image: haeho7/docker-images:nextcloud
    container_name: nextcloud
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      PUID: 99
      PGID: 100
      UMASK: 022
      MYSQL_HOST: '192.168.1.20:3306'
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: 'example'
      REDIS_HOST: '192.168.1.20'
      REDIS_HOST_PORT: 6379
      REDIS_HOST_PASSWORD: 'example'
      NEXTCLOUD_ADMIN_USER: example
      NEXTCLOUD_ADMIN_PASSWORD: 'example'
      NEXTCLOUD_TRUSTED_DOMAINS: '192.168.1.20 nextcloud.demo.com nextcloud.local.demo.com'
      PHP_MEMORY_LIMIT: 1024M
      PHP_UPLOAD_LIMIT: 0
    volumes:
      - ./nextcloud-data:/var/www/html
      - /mnt/user/datas/nextcloud:/var/www/html/data
