version: '3.9'

services:
  jellyfin:
    image: nyanmisaka/jellyfin:240106-amd64
    container_name: jellyfin
    network_mode: host
    restart: unless-stopped
    user: 99:100
    logging:
      options:
        max-file: 1
        max-size: 20m
    devices:
      - /dev/dri:/dev/dri
    environment:
      TZ: Asia/Shanghai
      JELLYFIN_PublishedServerUrl: 192.168.1.20
    #ports:
      #- 18096:8096
      #- 18920:8920
      #- 11900:1900/udp
      #- 17359:7359/udp
    volumes:
      - ./jellyfin-data:/config
      - /mnt/user/medias/moives:/data/movies:ro
      - /mnt/user/medias/series:/data/series:ro
      - /mnt/user/medias/tv:/data/tv:ro
      - /mnt/user/medias/acg:/data/acg:ro
