version: '3.9'

services:
  mdc:
    image: vergilgao/mdc:6.4.1-r0
    container_name: mdc
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      PUID: 99
      PGID: 100
      UMASK: 022
      TZ: Asia/Shanghai
    volumes:
      - ./mdc-data:/config
      - /mnt/user/9kg/scan:/data
