services:
  rsync-daemon:
    image: haeho7/docker-images:rsync
    container_name: rsync-daemon
    network_mode: host
    privileged: true
    restart: unless-stopped
    ulimits:
      nproc: -1
      nofile:
        soft: 1048576
        hard: 1048576
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      ENABLE_DAEMON: 1
      CRONTAB: '0 */12 * * * /srv/script/backup.sh > /proc/1/fd/1'
    volumes:
      - ./rsync-data:/srv
      #- ./rsync-data/conf/rsyncd.conf:/etc/rsyncd.conf
      #- ./rsync-data/conf/rsyncd.secrets:/etc/rsyncd.secrets
      - /mnt/user:/mnt/user:ro

  rsync-nas:
    image: haeho7/docker-images:rsync
    container_name: rsync-nas
    network_mode: host
    privileged: true
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      CRONTAB: '0 */12 * * * /srv/script/nas-backup.sh > /proc/1/fd/1'
    volumes:
      - ./rsync-data:/srv
      - /mnt/user:/mnt/user:ro
      - /mnt/cache_backup/backup/nas-data-backup:/mnt/cache_backup/backup/nas-data-backup

  rsync-unraid:
    image: haeho7/docker-images:rsync
    container_name: rsync-unraid
    network_mode: host
    privileged: true
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      CRONTAB: '0 */12 * * * /srv/script/unraid-backup.sh > /proc/1/fd/1'
    volumes:
      - ./rsync-data:/srv
      - /mnt/cache_backup/backup/unraid-data-backup:/mnt/cache_backup/backup/unraid-data-backup
