version: '3.9'

services:
  strongswan:
    image: pexcn/docker-images:strongswan
    container_name: strongswan
    network_mode: host
    privileged: true
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    #ports:
      #- 500:500/udp
      #- 4500:4500/udp
    environment:
      PSK: 'PreSharedKey'
      USERS: 'user1:password1,user2:password2'
      DEBUG: 0
