services:
  valkey:
    image: haeho7/docker-images:valkey
    container_name: valkey
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      PUID: 99
      PGID: 100
    volumes:
      - ./valkey-data/conf:/etc/valkey
      - ./valkey-data/data:/data
    command: valkey-server /etc/valkey/valkey.conf
