version: '3.9'

services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 192.168.1.240
    limits:
      memory: 2G
    environment:
      TZ: Asia/Shanghai
      PUID: 99
      PGID: 100
      UMASK: 022
      USER: example
      PASS: 'example'
      TRANSMISSION_WEB_HOME: /transmission-web-control/
      WHITELIST: '127.0.0.1,192.168.*.*'
      HOST_WHITELIST: '*.demo.com'
      PEERPORT: 51413
    # ports:
    #  - 9091:9091
    #  - 51413:51413
    #  - 51413:51413/udp
    volumes:
      - /mnt/user/appdata/transmission:/config
      - /mnt/user/torrent/:/downloads
      - /mnt/user/torrent/torrents_watch:/watch