services:
  gogs:
    image: gogs/gogs:0.13.3
    container_name: gogs
    restart: unless-stopped
    network_mode: host
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      PUID: 99
      PGID: 100
    volumes:
      - ./gogs-data:/data
