version: '3.9'

services:
  webdav:
    image: haeho7/docker-images:webdav
    container_name: webdav
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      PUID: 99
      PGID: 100
      USERNAME: example
      PASSWORD: 'example'
    volumes:
      - ./webdav-data:/config
      - /mnt/user/datas/webdav:/data
