version: '3.9'

services:
  webdav:
    image: haeho7/docker-images:webdav
    container_name: webdav
    network_mode: host
    restart: unless-stopped
    environment:
      PUID: 99
      PGID: 100
      UMASK: 000
      TZ: Asia/Shanghai
      USERNAME: example
      PASSWORD: 'example'
    volumes:
      - ./webdav-data:/config
      - /mnt/user/datas/webdav:/data
