version: '3.9'

services:
  webdav:
    image: pexcn/docker-images:webdav
    container_name: webdav
    restart: unless-stopped
    network_mode: host
    environment:
      PUID: 99
      PGID: 100
    volumes:
      - ./webdav-data/config.yml:/etc/webdav/config.yml
      - /mnt/data:/data
      - /etc/localtime:/etc/localtime:ro
