services:
  nginx:
    image: haeho7/docker-images:nginx
    container_name: nginx
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: 5
        max-size: 20m
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    labels:
      - me.local.container.name=nginx
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./nginx-data/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-data/conf.d:/etc/nginx/conf.d
      - ./nginx-data/http.d:/etc/nginx/http.d
      - ./nginx-data/stream.d:/etc/nginx/stream.d
      - ./nginx-data/html:/usr/share/nginx/html
      - /mnt/user/appdata/acme.sh/acme.sh-data:/cert
