version: '3.9'

services:
  ddns-go:
    image: jeessy/ddns-go:v4.3.4
    container_name: ddns-go
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./ddns-go-data:/root
