version: '3.9'

services:
  ddns-go:
    image: jeessy/ddns-go:v4.0.4
    container_name: ddns-go
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./ddns-go-data:/root
