version: '3.9'

services:
  wireguard:
    image: haeho7/docker-images:wireguard
    container_name: wireguard
    restart: unless-stopped
    network_mode: host
    privileged: true
    environment:
      USE_USERSPACE_MODE: 0
      PEER_RESOLVE_INTERVAL: 300
    volumes:
      - ./wireguard-data:/etc/wireguard
