version: '3.9'

services:
  wireguard:
    image: haeho7/docker-images:wireguard
    container_name: wireguard
    network_mode: host
    privileged: true
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
      PEER_RESOLVE_INTERVAL: 300
    volumes:
      - ./wireguard-data:/etc/wireguard
