version: '3.9'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.15
    container_name: adguardhome
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./adguardhome-data/conf:/opt/adguardhome/conf
      - ./adguardhome-data/work:/opt/adguardhome/work
