version: '3.9'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.11
    container_name: adguardhome
    restart: unless-stopped
    networks:
      br0:
        ipv4_address: 192.168.1.246
    limits:
      memory: 512M
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /mnt/user/appdata/adguardhome/conf:/opt/adguardhome/conf
      - /mnt/user/appdata/adguardhome/work:/opt/adguardhome/work
