version: '3.9'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.13
    container_name: adguardhome
    restart: unless-stopped
    networks: host
    limits:
      memory: 512M
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /mnt/user/appdata/adguardhome/conf:/opt/adguardhome/conf
      - /mnt/user/appdata/adguardhome/work:/opt/adguardhome/work
