version: '3.9'

services:
  adguardhome:
    image: adguard/adguardhome:v0.107.42
    container_name: adguardhome
    network_mode: host
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./adguardhome-data/conf:/opt/adguardhome/conf
      - ./adguardhome-data/work:/opt/adguardhome/work
