version: '3.9'

services:
  redis:
    image: haeho7/docker-images:redis
    container_name: redis
    restart: unless-stopped
    network_mode: host
    limits:
      memory: 512M
    environment:
      TZ: Asia/Shanghai
      PUID: 99
      PGID: 100
    volumes:
      - /mnt/user/appdata/redis:/data