version: '3.9'

services:
  redis:
    image: haeho7/docker-images:redis
    container_name: redis
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      PUID: 99
      PGID: 100
    volumes:
      - ./redis-data:/data
