version: '3.9'

services:
  vaultwarden:
    image: vaultwarden/server:1.30.1-alpine
    container_name: vaultwarden
    network_mode: host    
    restart: unless-stopped
    logging:
      options:
        max-file: 1
        max-size: 20m
    user: 99:100
    env_file: ./config.env
    environment:
      TZ: Asia/Shanghai
      ROCKET_ENV: production
      ADMIN_TOKEN: 'example'
    volumes:
      - ./vaultwarden-data:/data
