version: '3.9'

services:
  mariadb:
    image: haeho7/docker-images:mariadb
    container_name: mariadb
    network_mode: host
    restart: unless-stopped
    environment:
      PUID: 99
      PGID: 100
      TZ: Asia/Shanghai
      MARIADB_ROOT_PASSWORD: 'example'
      #MARIADB_DATABASE: example
      #MARIADB_USER: example
      #MARIADB_PASSWORD: 'example'
      #MARIADB_ROOT_HOST: '% localhost'
    volumes:
      - ./mariadb-data/conf.d/:/etc/mysql/conf.d
      - ./mariadb-data/data:/var/lib/mysql
