version: '3.9'

services:
  acme.sh:
    image: neilpang/acme.sh:3.0.4
    container_name: acme.sh
    restart: unless-stopped
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      DPI_ID: DNSPod ID
      DPI_Key: DNSPod Key
    command: daemon
    volumes:
      - ./acme.sh-data:/acme.sh
