version: '3.9'

services:
  acme.sh:
    image: neilpang/acme.sh:3.0.5
    container_name: acme.sh
    network_mode: host
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      DP_Id: 'example'
      DP_Key: 'example'
    command: daemon
    volumes:
      - ./acme.sh-data:/acme.sh
